# Generated by Django 5.1 on 2025-11-06 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.TextField(max_length=100)),
                ('creditos', models.PositiveIntegerField()),
                ('horario', models.CharField(max_length=50)),
                ('aula', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(max_length=50, unique=True)),
                ('apellido_profesor', models.CharField(max_length=50, unique=True)),
                ('correo_profesor', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('especialidad', models.CharField(default='', max_length=50)),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=50)),
                ('apellido_estudiante', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('correo_estudiante', models.EmailField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('cursos', models.ManyToManyField(related_name='estudiantes', to='app_Preparatoria.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='app_Preparatoria.profesor'),
        ),
    ]
