# Generated by Django 5.2.8 on 2025-11-16 20:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField(max_length=100)),
                ('creditos', models.PositiveIntegerField()),
                ('horario', models.CharField(max_length=50)),
                ('aula', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=50)),
                ('apellido_estudiante', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('correo_estudiante', models.EmailField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(max_length=50)),
                ('apellido_profesor', models.CharField(max_length=50)),
                ('correo_profesor', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('especialidad', models.CharField(default='', max_length=50)),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion_curso', models.DateField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('periodo_academico', models.CharField(default='2025-2', max_length=50)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Preparatoria.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Preparatoria.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'curso', 'periodo_academico')},
            },
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(related_name='estudiantes_inscritos', through='app_Preparatoria.Inscripcion', to='app_Preparatoria.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='app_Preparatoria.profesor'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evaluacion', models.CharField(choices=[('PARCIAL_1', 'Examen Parcial 1'), ('PARCIAL_2', 'Examen Parcial 2'), ('PROYECTO', 'Proyecto Final'), ('FINAL', 'Calificación Final'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_evaluacion', models.DateField(default=datetime.date.today)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('porcentaje_peso', models.PositiveIntegerField(default=100)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='app_Preparatoria.inscripcion')),
                ('profesor_asignador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_asignadas', to='app_Preparatoria.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('presente', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('justificacion_aprobada', models.BooleanField(default=False)),
                ('tipo_sesion', models.CharField(choices=[('CLASE', 'Clase Regular'), ('LAB', 'Laboratorio'), ('EXAMEN', 'Examen')], default='CLASE', max_length=20)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='app_Preparatoria.inscripcion')),
            ],
            options={
                'unique_together': {('inscripcion', 'fecha')},
            },
        ),
    ]
