# Generated by Django 5.1 on 2025-11-12 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Preparatoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion_curso', models.DateField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Preparatoria.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Preparatoria.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evaluacion', models.CharField(choices=[('PARCIAL_1', 'Examen Parcial 1'), ('PARCIAL_2', 'Examen Parcial 2'), ('PROYECTO', 'Proyecto Final'), ('FINAL', 'Calificación Final'), ('OTRO', 'Otro')], default='OTRO', max_length=50)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='app_Preparatoria.inscripcion')),
            ],
        ),
    ]
