# Generated by Django 5.1 on 2025-11-13 17:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Preparatoria', '0002_inscripcion_calificacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='porcentaje_peso',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='profesor_asignador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_asignadas', to='app_Preparatoria.profesor'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='es_obligatorio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='periodo_academico',
            field=models.CharField(default='2025-2', max_length=50),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha_evaluacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(related_name='estudiantes_inscritos', through='app_Preparatoria.Inscripcion', to='app_Preparatoria.curso'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellido_profesor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre_profesor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('estudiante', 'curso', 'periodo_academico')},
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('presente', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('hora_registro', models.TimeField(auto_now_add=True)),
                ('justificacion_aprobada', models.BooleanField(default=False)),
                ('tipo_sesion', models.CharField(choices=[('CLASE', 'Clase Regular'), ('LAB', 'Laboratorio'), ('EXAMEN', 'Examen')], default='CLASE', max_length=20)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='app_Preparatoria.inscripcion')),
            ],
            options={
                'unique_together': {('inscripcion', 'fecha')},
            },
        ),
    ]
